apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholaros-postgres
  namespace: scholaros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scholaros-postgres
  template:
    metadata:
      labels:
        app: scholaros-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: scholaros-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scholaros-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: scholaros-db-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: scholaros-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: scholaros-postgres
  namespace: scholaros
spec:
  selector:
    app: scholaros-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scholaros-postgres-pvc
  namespace: scholaros
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
